import type { Metadata } from "next";
import { LegalShell, H2 } from "@/components/legal-shell";

const SITE = process.env.NEXT_PUBLIC_SITE_URL ?? "https://translify.app";
const UPDATED = "2026-05-11";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The agreement between you and Translify when you use the service — what you can do, what you can't, payment terms, refunds, and limitations.",
  alternates: { canonical: "/terms" },
  openGraph: {
    title: "Terms of Service — Translify",
    description: "The agreement between you and Translify.",
    url: `${SITE}/terms`,
  },
};

export default function TermsPage() {
  return (
    <LegalShell
      title="Terms of Service"
      subtitle="The agreement between you and Translify when you use the service. Plain English, no tricks."
      lastUpdated={UPDATED}
    >
      <p>
        These terms apply when you use Translify. By creating an account or
        using the service, you agree to them. If you don't agree, please
        don't use the service.
      </p>

      <H2>1. Who can use Translify</H2>

      <p>
        You must be at least 13 years old to create an account. If you're
        creating an account on behalf of an organization, you confirm you
        have authority to bind that organization to these terms. The Family
        plan supports children's reading under a parent or guardian's
        account.
      </p>

      <H2>2. What you can use Translify for</H2>

      <p>
        Translify is a personal-study tool for translating, reading, and
        learning from books you legally own or have the right to use. You
        may:
      </p>

      <ul className="list-disc space-y-1 pl-6">
        <li>Upload PDFs and EPUBs of books you own or have lawfully acquired.</li>
        <li>Translate them into any supported language for your personal reading and study.</li>
        <li>Use the chat, highlight, AI explanation, and quiz features for your own learning.</li>
        <li>Download translated copies for your personal use.</li>
      </ul>

      <H2>3. What you can't use Translify for</H2>

      <p>You may not:</p>

      <ul className="list-disc space-y-1 pl-6">
        <li>Upload content you don't have the legal right to use — pirated books, content you've stolen, anything that infringes someone else's copyright.</li>
        <li>Redistribute translations as if they were your own work.</li>
        <li>Resell or commercially redistribute translated copies generated by Translify.</li>
        <li>Attempt to break, abuse, or reverse-engineer the service.</li>
        <li>Use the service to generate or distribute illegal, hateful, or harmful content.</li>
        <li>Share your account credentials with people outside your household (the Family plan exception aside).</li>
      </ul>

      <p>
        Violations of these rules can result in account suspension or
        termination without refund.
      </p>

      <H2>4. Your content</H2>

      <p>
        You retain all ownership rights to the books you upload and to the
        notes, highlights, and content you create inside Translify. By using
        the service you grant us a limited license to process your uploads
        for the sole purpose of operating the service for you — translating,
        embedding for chat, generating quizzes, displaying back to you. We
        do not claim any ownership of your content.
      </p>

      <p>
        We do not use your content to train any AI model, ours or anyone
        else's.
      </p>

      <H2>5. Subscriptions and payments</H2>

      <p>
        Translify is offered on a paid subscription basis with a 14-day free
        trial on every plan. Plans automatically renew at the end of each
        billing period unless cancelled. You can cancel any time from your
        account settings — your access continues through the period you've
        already paid for.
      </p>

      <p>
        Prices are shown on the{" "}
        <a href="/pricing" className="underline decoration-[color:var(--color-saffron)]/40">pricing page</a>.
        We may change prices with at least 30 days' notice to active
        subscribers; existing subscriptions keep their price for the current
        billing period.
      </p>

      <H2>6. Refunds</H2>

      <p>
        Every paid plan includes a 30-day money-back guarantee, no questions
        asked. To request a refund, reply to your welcome email or write to{" "}
        <a href="mailto:hello@translify.app" className="font-semibold underline decoration-[color:var(--color-saffron)]/40">hello@translify.app</a>{" "}
        within 30 days of your first paid charge. See the{" "}
        <a href="/refund-policy" className="underline decoration-[color:var(--color-saffron)]/40">refund policy</a> for details.
      </p>

      <H2>7. Service availability</H2>

      <p>
        We try hard to keep Translify available all the time, but we don't
        guarantee uninterrupted service. Maintenance, third-party outages,
        and the occasional incident will happen. We don't owe a refund for
        downtime under a few hours; for longer outages we credit affected
        accounts pro-rata.
      </p>

      <H2>8. AI-generated content disclaimers</H2>

      <p>
        Translation, chat answers, AI-explained highlights, and quiz
        questions are produced by AI models (currently Claude by Anthropic
        and DeepL). They are usually accurate but can make mistakes —
        especially on dense technical material, idioms, and unusual
        language pairs. Do not rely on Translify as the sole authority for
        legal, medical, financial, or other consequential decisions.
        Always verify against the source when accuracy matters.
      </p>

      <H2>9. Termination</H2>

      <p>
        You can delete your account at any time from account settings. We
        may suspend or terminate accounts that violate these terms, behave
        abusively toward our team, or trigger fraud signals (chargebacks,
        stolen cards). When an account is terminated we delete the account
        data within 30 days as described in our{" "}
        <a href="/privacy" className="underline decoration-[color:var(--color-saffron)]/40">privacy policy</a>.
      </p>

      <H2>10. Limitation of liability</H2>

      <p>
        Translify is provided &ldquo;as is.&rdquo; To the maximum extent
        permitted by applicable law, our total liability for any claim
        relating to the service is limited to the amount you paid us in the
        twelve months preceding the claim. We are not liable for indirect,
        consequential, or incidental damages.
      </p>

      <H2>11. Governing law</H2>

      <p>
        These terms are governed by the laws of France, without regard to
        conflict-of-laws principles. Disputes that cannot be resolved
        amicably will be brought before the competent courts in Paris,
        France — unless your local consumer-protection law gives you a
        different forum, in which case that law applies.
      </p>

      <H2>12. Changes to these terms</H2>

      <p>
        We may update these terms. Material changes are notified to active
        users by email at least 30 days before they take effect. Continued
        use of Translify after the change date constitutes acceptance.
      </p>

      <H2>13. Contact</H2>

      <p>
        Questions about these terms — email{" "}
        <a href="mailto:hello@translify.app" className="font-semibold underline decoration-[color:var(--color-saffron)]/40">hello@translify.app</a>.
      </p>
    </LegalShell>
  );
}
