import type { Metadata, Viewport } from "next";
import { Fraunces, Hanken_Grotesk } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { Providers } from "@/components/providers";
import { StructuredData } from "@/components/structured-data";

const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-fraunces",
  display: "swap",
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
});

const hanken = Hanken_Grotesk({
  subsets: ["latin"],
  variable: "--font-hanken",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const SITE = process.env.NEXT_PUBLIC_SITE_URL ?? "https://translify.app";

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#FAF6EE" },
    { media: "(prefers-color-scheme: dark)",  color: "#20283A" },
  ],
  width: "device-width",
  initialScale: 1,
  colorScheme: "light",
};

export const metadata: Metadata = {
  metadataBase: new URL(SITE),
  title: {
    default: "Translify — Understand any book, in any language",
    template: "%s · Translify",
  },
  description:
    "Read any PDF or EPUB in 14 languages with the layout preserved. Chat with the whole book and get cited answers, highlight passages for AI explanations in your language, and quiz yourself to remember what you read. 30-day money-back, no questions.",
  applicationName: "Translify",
  keywords: [
    "understand foreign language book AI",
    "AI study companion for books",
    "chat with foreign language book",
    "read books in another language with AI",
    "AI book reader for students",
    "AI book reader for researchers",
    "read Spanish books in English",
    "read German books in English",
    "read French books in English",
    "read Japanese books in English",
    "translate EPUB book AI",
    "translate PDF book layout preserved",
    "Translify app",
  ],
  authors: [{ name: "Translify", url: SITE }],
  creator: "Translify",
  publisher: "Translify",
  category: "Education",
  alternates: {
    canonical: "/",
    // hreflang alternates are emitted manually in <head> below — Next's
    // metadata.alternates.languages strips query strings, which collapses
    // every locale URL to the same canonical and breaks the signal.
  },
  openGraph: {
    type: "website",
    siteName: "Translify",
    title: "Translify — Understand any book, in any language",
    description:
      "Upload any PDF or EPUB. Read it in 14 languages with the layout preserved. Chat with the book, highlight for AI explanations, quiz yourself.",
    url: SITE,
    locale: "en_US",
    alternateLocale: ["fr_FR", "es_ES", "de_DE", "ja_JP", "zh_CN", "ar_SA", "id_ID", "ms_MY"],
    // Image is auto-generated by /opengraph-image.tsx — no static asset needed.
  },
  twitter: {
    card: "summary_large_image",
    title: "Translify — Understand any book, in any language",
    description:
      "Upload a PDF or EPUB. Read it in 14 languages with layout preserved. Chat with the book, highlight for AI explanations, quiz yourself.",
    site: "@translifyapp",
    creator: "@translifyapp",
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
  // icon.svg + auto-generated icon.tsx + apple-icon.tsx + opengraph-image.tsx
  // handle all icon/og asset needs. No 404s.
  icons: {
    icon: [{ url: "/icon.svg", type: "image/svg+xml" }],
  },
  manifest: "/manifest.webmanifest",
  formatDetection: {
    telephone: false,
    email: false,
    address: false,
  },
  other: {
    "format-detection": "telephone=no",
  },
};

// Set NEXT_PUBLIC_PLAUSIBLE_DOMAIN in production (e.g. "translify.app") to
// enable cookieless analytics. Leave unset locally — the script is skipped.
const PLAUSIBLE_DOMAIN = process.env.NEXT_PUBLIC_PLAUSIBLE_DOMAIN;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${fraunces.variable} ${hanken.variable}`}
    >
      <head>
        <StructuredData />
        {/* Plausible — cookieless, privacy-friendly analytics. Loads only
            when NEXT_PUBLIC_PLAUSIBLE_DOMAIN is set (production), so
            local development doesn't pollute production stats. */}
        {PLAUSIBLE_DOMAIN && (
          <script
            defer
            data-domain={PLAUSIBLE_DOMAIN}
            src="https://plausible.io/js/script.outbound-links.js"
          />
        )}
      </head>
      <body>
        <Providers>{children}</Providers>
        <Script id="facebook-pixel" strategy="afterInteractive">{`
          !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');
          fbq('init', '1289655489982440');
          fbq('track', 'PageView');
        `}</Script>
        <noscript>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img height="1" width="1" style={{ display: "none" }} src="https://www.facebook.com/tr?id=1289655489982440&ev=PageView&noscript=1" alt="" />
        </noscript>
      </body>
    </html>
  );
}
