import type { Metadata, Viewport } from "next";
import { Fraunces, Hanken_Grotesk } from "next/font/google";
import "./globals.css";
import "katex/dist/katex.min.css";
import { Providers } from "@/components/providers";
import { StructuredData } from "@/components/structured-data";

const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-fraunces",
  display: "swap",
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
});

const hanken = Hanken_Grotesk({
  subsets: ["latin"],
  variable: "--font-hanken",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const SITE = process.env.NEXT_PUBLIC_SITE_URL ?? "https://translify.app";

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#FAF6EE" },
    { media: "(prefers-color-scheme: dark)",  color: "#20283A" },
  ],
  width: "device-width",
  initialScale: 1,
  colorScheme: "light",
};

export const metadata: Metadata = {
  metadataBase: new URL(SITE),
  title: {
    default: "Translify — Study any book, in any language",
    template: "%s · Translify",
  },
  description:
    "Turn any textbook, paper, or PDF into a study workspace: a tutor that answers with cited pages, quizzes and flashcards built from what you read, a focus timer, and full translation in 14 languages. Start free, no card.",
  applicationName: "Translify",
  keywords: [
    "AI study app for students",
    "turn textbook into flashcards AI",
    "quiz yourself from your textbook",
    "AI tutor for any book",
    "study any book AI",
    "exam prep with AI",
    "chat with your textbook AI cited answers",
    "AI book reader for students",
    "AI book reader for researchers",
    "read Spanish books in English",
    "read German books in English",
    "read French books in English",
    "read Japanese books in English",
    "translate EPUB book AI",
    "translate PDF book layout preserved",
    "Translify app",
  ],
  authors: [{ name: "Translify", url: SITE }],
  creator: "Translify",
  publisher: "Translify",
  category: "Education",
  alternates: {
    canonical: "/",
    // hreflang alternates are emitted manually in <head> below — Next's
    // metadata.alternates.languages strips query strings, which collapses
    // every locale URL to the same canonical and breaks the signal.
  },
  openGraph: {
    type: "website",
    siteName: "Translify",
    title: "Translify — Study any book, in any language",
    description:
      "Turn any textbook, paper, or PDF into a study workspace: a tutor with cited answers, quizzes and flashcards from your reading, a focus timer, and translation in 14 languages.",
    url: SITE,
    locale: "en_US",
    alternateLocale: ["fr_FR", "es_ES", "de_DE", "ja_JP", "zh_CN", "ar_SA", "id_ID", "ms_MY"],
    // Image is auto-generated by /opengraph-image.tsx — no static asset needed.
  },
  twitter: {
    card: "summary_large_image",
    title: "Translify — Study any book, in any language",
    description:
      "Turn any textbook or PDF into a study workspace: cited tutor chat, quizzes and flashcards from your reading, a focus timer, and translation in 14 languages.",
    site: "@translifyapp",
    creator: "@translifyapp",
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
  // icon.svg + auto-generated icon.tsx + apple-icon.tsx + opengraph-image.tsx
  // handle all icon/og asset needs. No 404s.
  icons: {
    icon: [{ url: "/icon.svg", type: "image/svg+xml" }],
  },
  manifest: "/manifest.webmanifest",
  formatDetection: {
    telephone: false,
    email: false,
    address: false,
  },
  other: {
    "format-detection": "telephone=no",
  },
};

// Set NEXT_PUBLIC_PLAUSIBLE_DOMAIN in production (e.g. "translify.app") to
// enable cookieless analytics. Leave unset locally — the script is skipped.
const PLAUSIBLE_DOMAIN = process.env.NEXT_PUBLIC_PLAUSIBLE_DOMAIN;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${fraunces.variable} ${hanken.variable}`}
    >
      <head>
        <StructuredData />
        {/* Facebook Pixel */}
        <script
          dangerouslySetInnerHTML={{
            __html: `!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');fbq('init','1289655489982440');fbq('track','PageView');`,
          }}
        />
        <noscript>
          <img height="1" width="1" style={{ display: "none" }} src="https://www.facebook.com/tr?id=1289655489982440&ev=PageView&noscript=1" alt="" />
        </noscript>
        {/* Plausible — cookieless, privacy-friendly analytics. Loads only
            when NEXT_PUBLIC_PLAUSIBLE_DOMAIN is set (production), so
            local development doesn't pollute production stats. */}
        {PLAUSIBLE_DOMAIN && (
          <script
            defer
            data-domain={PLAUSIBLE_DOMAIN}
            src="https://plausible.io/js/script.outbound-links.js"
          />
        )}
      </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
